name: CI
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-24.04
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - run: zig build test
